# Generated by Django 3.0.8 on 2021-06-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobilenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
