# Generated by Django 3.0.8 on 2021-06-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksordered',
            name='deliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booksordered',
            name='returndate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownedbooks',
            name='expiryfrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownedbooks',
            name='expiryto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownedbooks',
            name='ownerfrom',
            field=models.DateField(blank=True, null=True),
        ),
    ]
