# Generated by Django 3.0.8 on 2021-06-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedbooks',
            old_name='expiryto',
            new_name='expiry',
        ),
        migrations.RemoveField(
            model_name='ownedbooks',
            name='expiryfrom',
        ),
    ]
