# Generated by Django 3.0.8 on 2021-06-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210603_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='duration',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
