# Generated by Django 3.0.8 on 2021-06-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210605_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='duration',
        ),
        migrations.AddField(
            model_name='booksordered',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownedbooks',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
