# Generated by Django 3.0.8 on 2021-06-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210606_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksordered',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
