# Generated by Django 3.0.8 on 2021-06-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_booksordered_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedbooks',
            name='returnvalue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
