# Generated by Django 3.0.8 on 2021-06-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_booksreturned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksreturned',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
