# Generated by Django 3.0.8 on 2021-06-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20210619_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershistory',
            name='returnedoninit',
            field=models.DateField(default=None),
        ),
    ]
