# Generated by Django 3.0.8 on 2021-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_ownershistory_returnedoninit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershistory',
            name='bookedon',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ownershistory',
            name='deliveredon',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ownershistory',
            name='returnedon',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ownershistory',
            name='returnedoninit',
            field=models.DateField(default=None, null=True),
        ),
    ]
