# Generated by Django 3.0.8 on 2021-06-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20210621_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownershistory',
            name='ownedbookid',
        ),
        migrations.RemoveField(
            model_name='ownershistory',
            name='returnedbookid',
        ),
        migrations.AddField(
            model_name='booksreturned',
            name='orderid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ownedbooks',
            name='orderid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ownershistory',
            name='orderid',
            field=models.IntegerField(default=0),
        ),
    ]
