# Generated by Django 3.0.8 on 2021-09-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20210621_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
